### ISSUE TITLE
Incompatible driver version 1.25.0

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbPlaywright#1]
I'm just getting started with cbPlaywright and noticed when I attempt to launch a browser (chromium or firefox), I get an error message:

_Incompatible driver version. cbPlaywright is using [1.25.0] while the driver is using [1.27.1]. Please update one or the other._

![image](https://user-images.githubusercontent.com/5341142/196555889-e154c7c5-1a23-4df9-a11c-ecd90837d119.png)

Sample test looks like this:
```
describe( "home page", () => {
	it( "can visit the home page", () => {
		var browser = variables.playwright.chromium().launch();
		var page = browser.newPage();
		navigate( page, "http://" & CGI.HTTP_HOST );
		waitForLoadState( page );
		expect( page.title() ).toBe( "Welcome to my site!" );
	} );
} );
```

**Comment by elpete** [comment]
`cbplaywright driver install 1.25.0 --force`

The driver in the included jars must match the installed driver.

Adding the above snippet would be a good add to this error message. (PR opportunity)

**Comment by homestar9** [comment]
@elpete Thanks for the heads up.  That command didn't work, though. This is what I received:
_Command "cbplaywright driver install 1.25.0 --force" cannot be resolved._
I also tried `playwright driver install 1.25.0 --force` since I think you meant to access the CLI, but received the following:
_error: unknown command 'driver'_

**Comment by elpete** [comment]
Nope, I definitely meant the `cbplaywright` namespace in CommandBox.  You access it by install `commandbox-cbplaywright`.

**Comment by bdw429s** [comment]
The name of the command isn't `cbplaywright`, it's `playwright-cli`

https://github.com/commandbox-modules/commandbox-cbplaywright/tree/main/commands

**Comment by homestar9** [comment]
@bdw429s, isn't `playwright-cli` also synonymous with `playwright`?

Either way: `playwright-cli driver install 1.25.0 --force` returns: _error: unknown command 'driver'_

**Comment by bdw429s** [comment]
> isn't playwright-cli also synonymous with playwright?

Yes, it is an alias.  I looked for that and missed it the first time.  

https://github.com/commandbox-modules/commandbox-cbplaywright/blob/main/commands/playwright-cli.cfc

> playwright-cli driver install 1.25.0 --force

Not sure.  Looking at the source, it seems to just be a simple passthrough to the real CLI.   You can see your arguments are just being passed through to the native `playwright.cmd` or `playwright.sh` (based on OS). 

https://github.com/commandbox-modules/commandbox-cbplaywright/blob/main/models/DriverService.cfc#L115 

So if 
```
/path/to/playwrite.sh foo bar
```
works, then presumably
```
CommandBox> playwright-cli foo bar
```
should also work. 

This error looks to be coming from Playwright itself

> error: unknown command 'driver'

If you just run the playwrite command on its own, you'll get the help output
```
❯ playwright-cli
run C:\Users\Brad\.CommandBox\cfml\modules\commandbox-cbplaywright/driver/playwright.cmd
Usage: npx playwright [options] [command]

Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  install-deps [options] [browser...]    install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
  screenshot [options] <url> <filename>  capture a page screenshot
  pdf [options] <url> <filename>         save page as pdf
  show-trace [options] [trace...]        show trace viewer
  test                                   Run tests with Playwright Test. Available in @playwright/test package.
  show-report                            Show Playwright Test HTML report. Available in @playwright/test package.
  help [command]                         display help for command

```

and the help for the `install` command

```
❯ playwright-cli install -h
run C:\Users\Brad\.CommandBox\cfml\modules\commandbox-cbplaywright/driver/playwright.cmd install -h
Usage: npx playwright install [options] [browser...]

ensure browsers necessary for this version of Playwright are installed

Options:
  --with-deps  install system dependencies for browsers
  --dry-run    do not execute installation, only print information
  --force      force reinstall of stable browser channels
  -h, --help   display help for command


Examples:
  - $ install
    Install default browsers.

  - $ install chrome firefox
    Install custom browsers, supports chromium, chrome, chrome-beta, msedge, msedge-beta, msedge-dev, firefox, webkit.
```
I don't see any documented playwright command called `driver install` so I'm guessing that was just a typo from @elpete

**Comment by elpete** [comment]
It looks like this module is missing an entire command. Let me figure out what happened to it, and I’ll push it up.

**Comment by elpete** [comment]
`commandbox-cbplaywright@1.1.0` has been released with the missing command.

**Comment by homestar9** [comment]
Thanks, Eric!

**Comment by bdw429s** [comment]
This issue has been mentioned on **Ortus Solutions Community**. There might be relevant details there:

https://community.ortussolutions.com/t/is-it-possible-to-coldbox-watch-one-folder-up-from-test-harness/9499/5
